[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brain-segmentation-tools"
version = "0.1.0"
requires-python = ">=3.10"
description = "A fast segmentation tool using synthetic data."
authors = [
    { name = "John Z", email = "johnz@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "monai",
    "nibabel",
    "scipy",
    "scikit-image",
    "fire",
    "numba",
    "cucim-cu12",
    "cupy-cuda12x",
    "platformdirs",
    "tqdm",
    "torch",

]

[tool.pytest.ini_options]
testpaths = ["brain_segmentation_tools", "test"]


[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff]
extend-exclude = ["dev"]

[tool.ty.src]
exclude = ["dev/freesurfer"]

[project.scripts]
synthseg = "brain_segmentation_tools.app:main"
synthseg-models = "brain_segmentation_tools.convert_models:main"

[tool.setuptools.packages.find]
include = ["brain_segmentation_tools*"]

[dependency-groups]
dev = [
    "loguru>=0.7.3",
    "h5py",
    "pytest",
    "ty"
]
