RESOURCE = {
    "labels": [
        0,
        3,
        3,
        5,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        2,
        3,
        3,
        4,
        4,
        6,
        1,
        7,
        7,
        8,
        8,
        1,
        1,
        1,
        0,
        3,
        3,
        1,
        2,
        3,
        3,
        4,
        4,
        6,
        1,
        7,
        7,
        8,
        8,
        1,
        1,
        1,
        0,
        3,
        3,
    ],
    "names": [
        "background",
        "general csf",
        "general csf",
        "brainstem",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "general white matter",
        "general grey matter",
        "general csf",
        "general csf",
        "cerebellum",
        "cerebellum",
        "thalamus",
        "general white matter",
        "putamen+pallidum",
        "putamen+pallidum",
        "hippocampus+amygdala",
        "hippocampus+amygdala",
        "general white matter",
        "general white matter",
        "general white matter",
        "background",
        "general csf",
        "general csf",
        "general white matter",
        "general grey matter",
        "general csf",
        "general csf",
        "cerebellum",
        "cerebellum",
        "thalamus",
        "general white matter",
        "putamen+pallidum",
        "putamen+pallidum",
        "hippocampus+amygdala",
        "hippocampus+amygdala",
        "general white matter",
        "general white matter",
        "general white matter",
        "background",
        "general csf",
        "general csf",
    ],
}
