RESOURCE = {
    "labels": [
        0,
        14,
        15,
        16,
        24,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        3,
        4,
        5,
        7,
        8,
        10,
        11,
        12,
        13,
        17,
        18,
        2,
        26,
        28,
        0,
        4,
        5,
        41,
        42,
        43,
        44,
        46,
        47,
        49,
        50,
        51,
        52,
        53,
        54,
        41,
        58,
        60,
        0,
        43,
        44,
    ],
    "names": [
        "background",
        "3rd ventricle",
        "4th ventricle",
        "brain-stem",
        "csf",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "background",
        "left cerebral white matter",
        "left cerebral cortex",
        "left lateral ventricle",
        "left inferior lateral ventricle",
        "left cerebellum white matter",
        "left cerebellum cortex",
        "left thalamus",
        "left caudate",
        "left putamen",
        "left pallidum",
        "left hippocampus",
        "left amygdala",
        "left cerebral white matter",
        "left accumbens area",
        "left ventral DC",
        "background",
        "left lateral ventricle",
        "left inferior lateral ventricle",
        "right cerebral white matter",
        "right cerebral cortex",
        "right lateral ventricle",
        "right inferior lateral ventricle",
        "right cerebellum white matter",
        "right cerebellum cortex",
        "right thalamus",
        "right caudate",
        "right putamen",
        "right pallidum",
        "right hippocampus",
        "right amygdala",
        "right cerebral white matter",
        "right accumbens area",
        "right ventral DC",
        "background",
        "right lateral ventricle",
        "right inferior lateral ventricle",
    ],
}
